name: Build Telegram Android

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Telegram
        run: |
          cd TMessagesProj
          ../gradlew assembleAfatDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Telegram-debug-apk
          path: TMessagesProj/build/outputs/apk/**/*.apk