name: Build Telegram Android

on:
  push:
    branches:
      - master

# اضافه کردن دسترسی برای ایجاد ریلیز در مخزن
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle' # فعال‌سازی کش گریدل برای افزایش سرعت بیلدهای بعدی

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant permission
        run: chmod +x gradlew

      - name: Build Telegram APK
        run: |
          ./gradlew :TMessagesProj_AppHuawei:assembleAfatDebug --stacktrace

      # تغییر نام فایل خروجی به Nigram.apk و انتقال آن به ریشه پروژه
      - name: Rename and Move APK to Nigram.apk
        run: |
          find TMessagesProj_AppHuawei/build/outputs/apk/ -name "*.apk" -exec cp {} ./Nigram.apk \;
          echo "فایل APK پیدا شد و با نام Nigram.apk ذخیره گردید."

      # آپلود آرتیفکت با نام جدید
      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Nigram-apk
          path: Nigram.apk

      # انتشار خودکار در صفحه Releases گیت‌هاب با نام Nigram.apk
      - name: Release APK on GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "build-${{ github.run_number }}"
          name: "Nigram Build #${{ github.run_number }}"
          body: "نسخه دیباگ نیگرام (Nigram) که به صورت خودکار ساخته شده است."
          draft: false
          prerelease: false
          files: Nigram.apk